[
  "error BatchError(bytes innerError)",
  "function batch(bytes[] calls, bool revertOnFail) payable"
]
